# Puerto donde correrá Java (para no chocar con el 5000 de Flask)
    server.port=8080

    # Configuración del servidor de correo (SMTP)
    spring.mail.host=smtp.gmail.com
    spring.mail.port=587
    spring.mail.username=cartuji7@gmail.com
    # ¡OJO! Aquí no va tu contraseña normal, va una "Contraseña de Aplicación"
    spring.mail.password=fozw urue typm fwho
    spring.mail.properties.mail.smtp.auth=true

    # Protocolos de seguridad
    
    spring.mail.properties.mail.smtp.starttls.enable=true